name: Test Analytics File Uploader
description: Uploads files to Buildkite Test Analytics
author: campspot
requirements: []
configuration:
  properties:
    artifact_location:
      type: string
    file_pattern:
      type: string
    dry_run:
      type: boolean
    buildkite_analytics_token:
      type: string